# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 469ff5f1a948a830853f74093f02be266a2a7d8c3247c94b521d4c70a2d06227407fa6f25edb025cee3f484506436a40af9a673f16c7082494a009ff0dc16e98

test:
  secret_key_base: 081c3fcdac170f1fa8418c1fa7efc63fc655349397545e205a63a3eed0db161807d688e9ed6edf99dafb29d36cc9b0192e755f712afe19f70c59d2b77ec7cc72

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
